### PR TITLE
add ability to specify the Organization, Directory, or Group in Password Reset function

### PR DESCRIPTION
**Pull request by shchiv**
Hi,

I have added an option to specify the Organization, Directory, or Group in Password Reset function,
(https://docs.stormpath.com/rest/product-guide/latest/accnt_mgmt.html#password-reset-flow).
It can be useful, for instance, when you use one application with few directories. Unfortunately, I cannot run your tests, because i'm using "Developer Plan", and I get the following message "Application limit reached".

Best regargs,
Igor

### CODE REVIEW

**Comment by shchiv** [comment]
Hi,
I am sorry to have kept you waiting for so long. 
I'll try to add the test cases as soon as possible.

Best regards,
Igor

**Comment by jarias** [comment]
No worries @shchiv

**Comment by jarias** [comment]
Thanks @shchiv since I don't have any plans to add any new functionality anytime soon, I'm doing a new release if all test pass I merge it to master today https://github.com/jarias/stormpath-sdk-go/pull/83 and your changes would be ready to used.

**Comment by shchiv** [comment]
Hi @jarias 
I have added few test cases and updated password reset for web version. 
But, I saw my test "TestPasswordResetWithAccStore" is failed (https://travis-ci.org/jarias/stormpath-sdk-go/jobs/202040672).
I'll try to fix it as soon as possible, but I can't understand how to link test dirictories with test application. 

Best regards,
Igor

**Comment by shchiv** [comment]
added the quick fix for "TestPasswordResetWithAccStore"

**Pull request merged**
