### PR TITLE
Some useful additions

### PR DESCRIPTION
**Pull request by ttousai**
Hello @jarias  this is the new PR against your develop branch.

### CODE REVIEW

**Comment by jarias** [comment]
Pleas look at the comment on f142561 looks like your behind from whats in the develop branch. Can you sync and re-send the PR

**Comment by jarias** [comment]
I cherry pick the commits and merge them, all but eba545a still not sure about it

**Comment by ttousai** [comment]
Hey. The idea with https://github.com/jarias/stormpath-sdk-go/commit/eba545aadbf3c6de72f042623580dfbfcdcc254e is to expose your stormpathError type to clients of the sdk. 

I think the should return the complete stormpath error struct to sdk clients so they can do special processing based on what the stormpath error is (based on error codes from stormpath). The current incarnation of the sdk just logs the error message and returns a plain error.

By implementing Error interface (instead or inspite String) on the stormpathError struct and making it public you can return stormpathError as type error and achieve the above goal, check out http://blog.golang.org/error-handling-and-go

**Comment by jarias** [comment]
I think it makes sense I put a comment in the commit let me know what you think about it.

**Comment by ttousai** [comment]
:`( 

I can' the commit and comment, could you please share a link?

**Comment by jarias** [comment]
Can't see it? is in the time line of this PR, anyways here is the link https://github.com/ttousai/stormpath-sdk-go/commit/eba545aadbf3c6de72f042623580dfbfcdcc254e#diff-f07344ec6a1dc5736ec5f4babaea0795R56

**Pull request closed without merging**
