### PR TITLE
Release 0.1.0-beta.13

### PR DESCRIPTION
**Pull request by jarias**
Changelog 

- Fix for #20 
- Replace Redis cache impl with a Ledis one #18

### CODE REVIEW

**Comment by dfwmountainbiker** [comment]
Why would you replace redis with Ledis? I understand it's "cool", but if one is going to implement in their architecture - they're almost certainly using redis - and wouldn't want yet another dependency.

**Comment by jarias** [comment]
@dfwmountainbiker Actually not having a external dependency is the reason to use ledis, as a contributor I don't need setup external servers to run the test suite. I'm not sure that Redis would be what everyone is going to use in production. It does adds an extra dep but for people not using Redis it was also the case before.

**Comment by superaaron** [comment]
Hi Julio,

Hope all is well in Costa Rica (and Happy Holidays!).  I tried to upgrade () and started getting a bunch of errors related to missing functions/methods.  I was using:

{
   "ImportPath": "github.com/jarias/stormpath-sdk-go",
   "Comment": "0.1.0-beta.4-33-g1fc9397",
   "Rev": "1fc93975b3659f8bacff6f4478190b0c09bba22f"
},
but tried to upgrade to:
{
   "ImportPath": "github.com/jarias/stormpath-sdk-go",
   "Comment": "0.1.0-beta.12-5-g76811b6",
   "Rev": "76811b67e364c96891289a3d7228353a005d1a89"
},
just to give you some context.

My question is (for now): What is the new version’s equivalent of AccountRef.Refresh()?  Or is that no longer necessary to use so it was removed from the new version?

Thanks,
Aaron

**Comment by jarias** [comment]
Hi Aaron,

Happy holidays to you too.

```AccountRef``` is no longer return by any public function actually that type is now private ```accountRef```, you can always load any resource by it's href by a function GetRESOURCE(href, criteria) for example https://github.com/jarias/stormpath-sdk-go/blob/master/account.go#L62 The criteria struct is a way to specify things like filtering or attribute expansion of the given resource see https://github.com/jarias/stormpath-sdk-go/blob/master/account_criteria.go

A simple way to load an account by href would be 

```
import "github.com/jarias/stormpath-sdk-go"

account, err := stormpath.GetAccount("https://something_something", stormpath.MakeAccountCriteria())
```

Also each resource has a Refresh() function that reloads the resource from Stormpath API

https://github.com/jarias/stormpath-sdk-go/blob/master/account.go#L79

Hope this helps. I don't expect a lot of API changes from now on, just adding support for missing resources like Organizations and such.

**Comment by superaaron** [comment]
cool, i will check it out.  i noticed something else:

OLD: Rev: “76811b67e364c96891289a3d7228353a005d1a89"
	//Groups represent a paged result of groups
	type Groups struct {
		collectionResource
		Items []Group `json:"items"`
	}

NEW: Rev: "1fc93975b3659f8bacff6f4478190b0c09bba22f"
	//Groups represent a paged result of groups
	type Groups struct {
		list
		Items []Groups `json:"items"`
	}

The Items in the first is defined as []Group, while in the latter it is defined as  []Groups (i.e., refers to itself).

I have code that looks like this:

for _, group := range groups.Items {
 if group.Name == groupName {
  return &group, nil
 }
}
that can no longer access the group.Name because group is really a []Groups now.

**Comment by jarias** [comment]
@superaaron That is fix in the latest https://github.com/jarias/stormpath-sdk-go/blob/master/group.go#L18

**Comment by superaaron** [comment]
I ran 'godep update github.com/jarias/stormpath-sdk-go' but it did not pick this up.  What revision number should i use in my Godeps.json for the latest stable build?

The update got me this version of the repo:
{
   "ImportPath": "github.com/jarias/stormpath-sdk-go",
   "Comment": "0.1.0-beta.4-33-g1fc9397",
   "Rev": "1fc93975b3659f8bacff6f4478190b0c09bba22f"
},
Is that not there latest release?

Thanks!

**Comment by jarias** [comment]
@superaaron Latest release is 0.1.0-beta.13 which is actually the PR we are discussing this. Looks like Godeps is not really updating the dependency.

**Pull request merged**
